from mapa import MAPA


BLOCO_ALTURA = 30
BLOCO_LARGURA = 30
ALTURA = len(MAPA[0]) * 30 
LARGURA = len(MAPA) * BLOCO_LARGURA +50
COMIDINHA_HEIGHT = 30
COMIDINHA_WIDTH = 30
COMIDA_HEIGHT = 30
COMIDA_WIDTH = 30